<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Wrapmax 404 Gutenverse Hero', 'wrapmax' ),
	'categories' => array( 'wrapmax-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-fq1w3g","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-10"}},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":67,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/squere-07.webp"}},"position":{"Desktop":"custom","Tablet":"custom","Mobile":"center center"},"yposition":{"Desktop":{"point":"215","unit":"px"},"Tablet":{"point":"177"}},"xposition":{"Desktop":{"point":"20","unit":"%"}},"repeat":{"Desktop":"repeat-x"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"point":"24","unit":"%"},"Tablet":{"unit":"%","point":"40"},"Mobile":{"unit":"%","point":"80"}}},"opacity":"0.1","margin":{"Desktop":{"unit":"px"},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"280","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"top":"200","bottom":"150","right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"200","bottom":"150"}}}} -->
<div class="section-wrapper" data-id="fq1w3g"><section class="wp-block-gutenverse-section guten-element guten-section guten-fq1w3g layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-w45BhC"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-w45BhC"><div class="guten-column-wrapper" data-id="w45BhC"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-g54dSi"} -->
<div class="section-wrapper" data-id="g54dSi"><section class="wp-block-gutenverse-section guten-element guten-section guten-g54dSi layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-Qp3M0x","verticalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Qp3M0x"><div class="guten-column-wrapper" data-id="Qp3M0x"><!-- wp:gutenverse/heading {"elementId":"guten-TnHpwU","type":5,"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"4UYYmg","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"transform":"capitalize","spacing":{"Desktop":"-.02"}},"containsAnchorTag":false,"background":{"type":"default","color":{"type":"variable","id":"theme-5"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"14","left":"14","bottom":"8","top":"7"}}},"positioningType":{"Desktop":"inline"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-TnHpwU">Error 404</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-6sqq8L","type":1,"textAlign":{"Tablet":"center","Desktop":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"2RKE7q","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"108","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.1"}},"weight":"500","transform":"capitalize"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"full"},"textChilds":[{"color":{"type":"variable","id":"theme-5"},"colorHover":[],"typography":{"type":"variable","id":"a7vmAC","font":{"label":"Lato","value":"Lato","type":"google"},"size":{"Desktop":{"point":"84","unit":"px"}},"weight":"700","transform":"capitalize","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}}},"typographyHover":[],"textClip":[],"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-E1iIcl","spanId":"guten-2RBj7a","_key":"pkxscz","borderNormal":{"Desktop":{"radius":[]}}}],"openChild":"guten-E1iIcl"} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-6sqq8L">Page Not Found<span id="guten-2RBj7a"><span class="guten-text-highlight guten-Kxfqp4" id="guten-E1iIcl">.</span></span></h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-XyJ77j","columns":{"Desktop":"1","Tablet":""},"gap":{"Tablet":{"unit":"px"},"Mobile":{"unit":"px"},"Desktop":{"unit":"px"}},"alignment":{"Desktop":"center"},"textColor":{"r":255,"g":255,"b":255,"a":0.7019607843137254},"typography":{"font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"20","unit":"px"},"Mobile":{"point":"16","unit":"px"},"Tablet":{"unit":"px"}},"lineHeight":{"Desktop":{"unit":"px","point":"30"},"Mobile":{"unit":"px"}},"weight":"400","transform":"normal","style":"normal","decoration":"none","spacing":{"Desktop":""}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"px"}},"positioningType":{"Desktop":"full"},"positioningWidth":{"Desktop":{"point":"552","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-XyJ77j"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Oops! Please go back home to find what you need.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-vikC9K","content":"Back To Home","url":"#","paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"45","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"gradient","color":{"r":152,"g":109,"b":248,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(255, 183, 31, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"buttonBackgroundHover":{"type":"gradient","color":{"r":134,"g":81,"b":250,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(199, 255, 31, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none"}},"showIcon":true,"icon":"gtn gtn-right-arrow1-light","iconPosition":"after","iconSpacing":{"Desktop":"20"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"300"},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"5yD1iV","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.02"},"weight":"600"},"positioningType":{"Desktop":"inline"},"transform":{"moveXHover":{"Desktop":{"point":"10","unit":"px"}}}} -->
<div class="guten-element guten-button-wrapper guten-vikC9K"><a class="guten-button guten-button-sm" href="#"><span>Back To Home</span><i class="fa-lg gtn gtn-right-arrow1-light"></i></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
