<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Wrapmax Search Gutenverse Hero', 'wrapmax' ),
	'categories' => array( 'wrapmax-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1000"},"gap":"no","elementId":"guten-NuIaQJ","background":{"type":"default","color":{"type":"variable","id":"theme-10"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":52,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/squere-03.webp"},"Tablet":[]},"position":{"Desktop":"custom","Tablet":"custom","Mobile":"center center"},"repeat":{"Desktop":"repeat-y"},"size":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"width":{"Desktop":{"unit":"%","point":"27"},"Tablet":{"unit":"%","point":"35"},"Mobile":{"unit":"%","point":"60"}},"xposition":{"Desktop":{"unit":"%","point":"75.7"},"Tablet":{"unit":"%","point":"85"}},"yposition":{"Desktop":{"point":"0","unit":"px"}}},"opacity":"0.1","border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"100","left":"100"}}}},"borderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"bottom":"80","left":"80"}}},"Mobile":{"radius":{"unit":"px","dimension":{"bottom":"60","left":"60"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"205","bottom":"145"}},"Tablet":{"unit":"px","dimension":{"right":"35","left":"35","top":"135","bottom":"100"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"zIndex":{"Desktop":null}} -->
<div class="section-wrapper" data-id="NuIaQJ"><section class="wp-block-gutenverse-section guten-element guten-section guten-NuIaQJ layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-HV0l0X","verticalAlign":{"Desktop":"flex-start"},"horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"zIndex":{"Desktop":5}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HV0l0X"><div class="guten-column-wrapper" data-id="HV0l0X"><!-- wp:gutenverse/search-result-title {"elementId":"guten-xxFcne","alignment":{"Desktop":"center"},"typography":{"type":"variable","id":"geDW0k","size":{"Desktop":{"point":"48","unit":"px"}},"weight":"600","lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"transform":"capitalize"},"color":{"type":"variable","id":"white"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px"}}} -->
<div class="guten-element guten-search-result-title guten-xxFcne"></div>
<!-- /wp:gutenverse/search-result-title -->

<!-- wp:gutenverse/search {"elementId":"guten-Q81g2f","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"150","unit":"px"},"Mobile":[]},"positioningType":{"Desktop":"inline","Mobile":"default"},"positioningWidth":{"Desktop":{"point":"482","unit":"px"}},"border":{"radius":{"Desktop":[]},"all":{"type":"none","width":1,"color":{"r":255,"g":255,"b":255,"a":0.2}}},"borderResponsive":{"Mobile":{"radius":[]}},"borderHover":{"radius":{"Desktop":[]},"all":{"type":"none","width":1,"color":{"type":"variable","id":"n2KAia"}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"animation":{"type":{"Desktop":"none"},"delay":200,"duration":"normal"},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-11"}},"inputPlaceholder":"Search blog...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"15","bottom":"","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":""}},"Tablet":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"inputHeight":{"Desktop":"60","Tablet":"","Mobile":"50"},"inputWidth":{"Desktop":{"point":"450","unit":"px"},"Mobile":{"unit":"%","point":""},"Tablet":{"unit":"px","point":"375"}},"inputTypography":{"type":"variable","id":"D5ratU","size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.9"}},"font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"all":{"type":"none","width":1,"color":{"type":"variable","id":"CG0xnK"}}},"inputBorderNormalResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"Tablet":{"radius":[]}},"inputColorHover":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"white"}},"inputBgColorHover":{"Desktop":[]},"inputAreaBoxShadow":{"vertical":"1","blur":"2","color":{"r":0,"g":0,"b":0,"a":0.05}},"alignContent":{"Desktop":"center"}} -->
<div class="guten-element guten-Q81g2f guten-search"><form class="gutenverse-search-form"><div class="search-input-container"><input type="text" placeholder="Search blog..." name="s" class="gutenverse-search gutenverse-search-input"/><div class="close-icon"><i class="gtn gtn-x-line"></i></div></div><!-- wp:gutenverse/button {"elementId":"guten-Skdipm","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"buttonHeight":{"Desktop":"60","Mobile":"50"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":""}},"Mobile":[],"Tablet":[]},"buttonBackground":{"color":{"type":"variable","id":"nXpoJb"},"type":"gradient","gradientColor":[{"color":"rgba(252, 252, 252, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(255, 183, 31, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"buttonBackgroundHover":{"type":"gradient","color":{"type":"variable","id":"tPgBZv"},"gradientColor":[{"color":"rgba(255, 255, 255, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(199, 255, 31, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"buttonBorderResponsive":{"Mobile":{"radius":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"buttonBoxShadow":{"vertical":"0","blur":"0","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","left":"15","right":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"5yD1iV","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.02"},"weight":"600"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-button-wrapper guten-Skdipm"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
