<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Wrapmax Gutenverse Newsletter', 'wrapmax' ),
	'categories' => array( 'wrapmax-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","gap":"no","elementId":"guten-LDWDbf","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-10"}}} -->
<div class="section-wrapper" data-id="LDWDbf"><section class="wp-block-gutenverse-section guten-element guten-section guten-LDWDbf layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-ycr15X"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ycr15X"><div class="guten-column-wrapper" data-id="ycr15X"><!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-GPwbXF","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"bottom":"100","left":"100"}}}},"borderResponsive":{"Tablet":{"radius":{"unit":"px","dimension":{"bottom":"80","left":"80"}}},"Mobile":{"radius":{"unit":"px","dimension":{"bottom":"60","left":"60"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"35","bottom":"60","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"50","right":"25","bottom":"50","left":"25"}}}} -->
<div class="section-wrapper" data-id="GPwbXF"><section class="wp-block-gutenverse-section guten-element guten-section guten-GPwbXF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":48},"elementId":"guten-5KAQys","verticalAlign":{"Desktop":"default","Tablet":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Mobile":{"unit":"px","dimension":{"bottom":"20"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5KAQys"><div class="guten-column-wrapper" data-id="5KAQys"><!-- wp:gutenverse/icon-list {"elementId":"guten-4Yttas","displayInline":true,"verticalAlign":"flex-start","iconColor":{"type":"variable","id":"theme-3"},"iconSize":{"Desktop":"15","Tablet":"12"},"textColor":{"type":"variable","id":"theme-11"},"textIndent":{"Desktop":"12","Tablet":"4"},"textTypography":{"type":"variable","id":"D5ratU","size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.9"}},"font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningWidth":{"Desktop":{"point":"445","unit":"px"}},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-icon-list guten-4Yttas"><div class=" list-wrapper inline-icon-list"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-qOoEVJ","textChilds":[{"color":{"type":"variable","id":"theme-0"},"colorHover":[],"typography":{"type":"variable","id":"zMtfZW","font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"16","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.9"}},"decoration":"none"},"typographyHover":[],"textClip":[],"textClipHover":[],"textStroke":[],"textStrokeHover":[],"background":[],"backgroundHover":[],"padding":[],"paddingHover":[],"margin":[],"marginHover":[],"value":[],"id":"guten-0bS1L2","spanId":"guten-HssZNy","_key":"nMlncg"}],"iconLineHeight":{"Desktop":"34"}} -->
<div class="guten-element guten-icon-list-item guten-qOoEVJ"><div class="list-divider"></div><a id="guten-qOoEVJ"><i class="fas fa-circle"></i><span class="list-text "><span id="guten-HssZNy"><span class="guten-text-highlight guten-gBHmtY" id="guten-0bS1L2">Subscribes</span></span> our daily newsletter!</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":52},"elementId":"guten-KMGpvU","horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-end"},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-KMGpvU"><div class="guten-column-wrapper" data-id="KMGpvU"><!-- wp:gutenverse/form-builder {"elementId":"guten-F06HVd","formId":{"label":"Newsletter Form","value":193},"border":{"radius":{"Tablet":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":[],"Desktop":[],"Mobile":[]}} -->
<form style="display:none" class="guten-element guten-form-builder guten-F06HVd" data-form-id="193"><!-- wp:gutenverse/form-input-email {"elementId":"guten-dsEKy5","showLabel":false,"showHelper":false,"labelColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"labelPadding":{"Desktop":[],"Tablet":[]},"labelMargin":{"Desktop":[],"Tablet":[]},"helperPadding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"87"},"Tablet":{"point":"280","unit":"px"},"Mobile":{"point":"74","unit":"%"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"all":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputPlaceholder":"Enter your email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","bottom":"13","left":"30","right":"25"}},"Mobile":{"unit":"px","dimension":{"top":"18","bottom":"16","left":"20","right":""}}},"inputMargin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":""}}},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-11"}},"inputTypography":{"type":"variable","id":"D5ratU","size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.9"}},"font":{"label":"Plus Jakarta Sans","value":"Plus Jakarta Sans","type":"google"}},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"all":{"type":"solid","width":"0"}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputColorFocus":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderFocus":{"radius":{"Desktop":[]}},"inputBgColorNormal":{"Desktop":{"r":248,"g":248,"b":248,"a":1}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-dsEKy5 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Enter your email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-cJcz2k","content":"","buttonWidth":{"Mobile":"","Desktop":"","Tablet":""},"buttonBackground":{"type":"gradient","color":{"type":"variable","id":"theme-3"},"gradientColor":[{"color":"rgba(241, 92, 69, 1)","active":true,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(196, 58, 19, 1)","opacity":1,"active":false,"id":2,"offset":"1.000"}]},"buttonBackgroundHover":{"type":"gradient","color":{"type":"variable","id":"theme-9"},"gradientColor":[{"color":"rgba(191, 219, 119, 1)","opacity":1,"active":true,"id":1,"offset":"0.000"},{"color":"rgba(143, 187, 86, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"110","right":"110","bottom":"110","left":"110"}}},"all":{"type":"none","width":"1","color":{"r":80,"g":65,"b":74,"a":1}}},"showIcon":true,"icon":"fab fa-telegram-plane","iconSize":{"Desktop":{"point":"22","unit":"px"}},"positioningType":{"Desktop":"inline","Mobile":"custom"},"positioningWidth":{"Mobile":{"point":"","unit":"px"},"Desktop":{"point":"","unit":"px"}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Mobile":[]},"color":{"r":255,"g":255,"b":255,"a":1},"typography":{"font":{"label":"Muli","value":"Muli","type":"google"},"size":{"Desktop":{"point":"12","unit":"px"}},"lineHeight":{"Desktop":{"point":"21.6","unit":"px"}},"weight":"500","transform":"uppercase","spacing":{"Desktop":"0.125"}},"hoverTextColor":{"r":255,"g":255,"b":255,"a":1},"alignButton":{"Tablet":null},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"19","bottom":"19","right":"19","left":"19"}},"Mobile":{"unit":"px","dimension":{"top":"18","right":"","bottom":"18","left":""}},"Tablet":[]},"iconLineHeight":true} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-cJcz2k"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><i class="fa-lg fab fa-telegram-plane"></i><span></span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => true,
);
